### ISSUE TITLE
Error: Need to call TestBed.initTestEnvironment() first

### ISSUE THREAD

**Issue by juniorschen** [jcassidyav/nativescript-testing-demo#1]
Error: Need to call TestBed.initTestEnvironment() first

following the instructions, any help?

**Comment by jcassidyav** [comment]
@juniorschen This repo was a little out of date, you can take a look at the docs https://docs.nativescript.org/development-workflow.html#testing 
or a later blog post https://blog.nativescript.org/unit-testing-with-v3-runner/

I've updated this repo now so it works with the latest.
